version: 0.2

phases:
  install:
    commands:
      - sudo apt install nodejs
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  base-directory: build/
  files:
    - '**/*'
