version: 0.2

phases:
  install:
    commands:
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
      - . ~/.nvm/nvm.sh
      - command -v nvm
  pre_build:
    commands:
      - nvm install 4.4.5
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  base-directory: build/
  files:
    - '**/*'
